---
- name: add localhost to inventory file
  add_host:
    name: "localhost"
    groups: "local"
    ansible_connection: "local"

- include_tasks: tasks/copykeys.yml
  vars:
      hostname: "{{ undercloud_hostname }}"

- name: get python interpreter
  shell: |
      ssh {{ ansible_ssh_user }}@{{ undercloud_hostname }} /usr/bin/python --version
  register: python_version
  ignore_errors: true

- name: python interpreter
  set_fact:
      python_interpreter: "{{ (python_version.stderr_lines|length > 0) | ternary('/usr/libexec/platform-python', '/usr/bin/python') }}"

- name: add undercloud_host to inventory file
  add_host:
      name: "{{ undercloud_hostname }}"
      groups: "baremetal,undercloud,tester"
      ansible_host: "{{ undercloud_hostname }}"
      ansible_user: "{{ ansible_ssh_user }}"
      ansible_ssh_private_key_file: "{{ ansible_ssh_key }}"
      ansible_python_interpreter: "{{ python_interpreter }}"

- name: generate inventory file
  template:
      dest: "{{ infrared_hosts_dir }}/{{ inventory_file_name }}"
      src: inventory.j2

- name: update inventory file symlink
  file:
      dest: "{{ infrared_hosts_file }}"
      state: link
      src: "{{ inventory_file_name }}"
