---
  - name: Update quotas
    vars:
      ansible_python_interpreter: "/var/tmp/venv_shade/bin/python"
    os_quota:
      cloud: overcloud
      name: admin
      backup_gigabytes: -1
      backups: -1
      cores: -1
      fixed_ips: -1
      floating_ips: -1
      gigabytes: -1
      injected_file_size: -1
      injected_files: -1
      injected_path_size: -1
      instances: -1
      port: -1
      key_pairs: -1
      per_volume_gigabytes: -1
      properties: -1
      ram: -1
      security_group_rule: -1
      security_group: -1
      server_group_members: -1
      server_groups: -1
      snapshots: -1
      volumes: -1
    delegate_to: "{{ groups.shade | first }}"
